import { createClient, SupabaseClient } from '@supabase/supabase-js';

// Supabase configuration
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || '';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || '';

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn('⚠️ Missing Supabase environment variables. Auth features will not work.');
  console.warn('Please set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in .env.local or Vercel env vars.');
}

// Create a single supabase client for interacting with your database
// Use a safe initialization that won't crash the app
let supabase: SupabaseClient;
try {
  supabase = createClient(supabaseUrl || 'https://placeholder.supabase.co', supabaseAnonKey || 'placeholder', {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true
    }
  });
} catch (e) {
  console.error('Failed to initialize Supabase client:', e);
  // Create a minimal client that won't crash the app
  supabase = createClient('https://placeholder.supabase.co', 'placeholder');
}

export { supabase };

// Database types (will be auto-generated by Supabase CLI in production)
export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          name: string;
          university: string | null;
          major: string | null;
          avatar_color: string;
          xp: number;
          level: number;
          literacy_progress: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          name: string;
          university?: string | null;
          major?: string | null;
          avatar_color?: string;
          xp?: number;
          level?: number;
          literacy_progress?: number;
        };
        Update: {
          name?: string;
          university?: string | null;
          major?: string | null;
          avatar_color?: string;
          xp?: number;
          level?: number;
          literacy_progress?: number;
        };
      };
      reflection_entries: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          answers: Record<string, string>;
          ai_analysis: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          date?: string;
          answers: Record<string, string>;
          ai_analysis?: string | null;
        };
        Update: {
          answers?: Record<string, string>;
          ai_analysis?: string | null;
        };
      };
      literacy_topics: {
        Row: {
          id: string;
          title: string;
          description: string;
          icon: string;
          xp_reward: number;
          content: string | null;
          order_index: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
      };
      literacy_progress: {
        Row: {
          id: string;
          user_id: string;
          topic_id: string;
          completed: boolean;
          completed_at: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          topic_id: string;
          completed?: boolean;
          completed_at?: string | null;
          notes?: string | null;
        };
        Update: {
          completed?: boolean;
          completed_at?: string | null;
          notes?: string | null;
        };
      };
      projects: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          description: string | null;
          content: string | null;
          status: string;
          ai_feedback: string | null;
          submitted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          title: string;
          description?: string | null;
          content?: string | null;
          status?: string;
          ai_feedback?: string | null;
        };
        Update: {
          title?: string;
          description?: string | null;
          content?: string | null;
          status?: string;
          ai_feedback?: string | null;
          submitted_at?: string | null;
        };
      };
      community_posts: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          content: string;
          category: string;
          likes_count: number;
          comments_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          title: string;
          content: string;
          category?: string;
        };
        Update: {
          title?: string;
          content?: string;
          category?: string;
        };
      };
      badges: {
        Row: {
          id: string;
          name: string;
          description: string;
          icon: string;
          requirement_type: string;
          requirement_value: number;
          created_at: string;
        };
      };
      user_badges: {
        Row: {
          id: string;
          user_id: string;
          badge_id: string;
          earned_at: string;
        };
      };
    };
  };
}
